name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v2with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: npm i
      - run: npm run tw:build
      - run: mkdocs gh-deploy --force
